config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    sessions: "users/sessions", 
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "users/registrations"
  }

  resources :events, :only => [:create]
  get 'e/:id' => 'events#show', as: :event
  get 'e/:id/edit' => 'events#edit', as: :edit_event
  patch 'e/:id' => 'events#update'
  put 'e/:id' => 'events#update'
  
  resources :bookings, :only => [:create, :destroy]

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
    end
  end

  resources :messages, only: [:new, :create]

  root 'pages#home'

  get 'faq' => 'pages#faq', as: :faq

  get 'dashboard' => 'users#dashboard', as: :dash

  get 'c/:city' => 'events#city', as: :city

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  attr_accessor :current_password

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  validates :firstname, presence: true

  acts_as_messageable
  
  has_many :events

  def name
    self.firstname
  end

  def mailboxer_email(object)
    self.email
  end

  def self.from_omniauth(auth)

    name = (auth.info.name).split
	  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.email = auth.info.email
	    user.password = Devise.friendly_token[0,20]
	    user.firstname = name.first
      if name.count > 1
        user.lastname = name[1..-1].join
      end
	    user.avatar = auth.info.image 
	  end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  invisible_captcha only: [:create]
  before_filter :configure_sign_up_params, only: [:create]
  before_filter :configure_account_update_params, only: [:update]

  def update
    # For Rails 4
    #account_update_params = devise_parameter_sanitizer.sanitize(:account_update)
    # For Rails 3
    # account_update_params = params[:user]

    # required for settings form to submit when password is left blank

    @user = User.find(current_user.id)
    unless @user.blank?
      if update_resource(account_update_params)
        set_flash_message :notice, :updated
        # Sign in the user bypassing validation in case their password changed
        sign_in @user, :bypass => true
        redirect_to edit_user_registration_path 
      else
        render "edit"
      end
    else 
      render "edit"
    end
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # You can put the params you want to permit in the empty array.
  def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) << :firstname
  end

  #You can put the params you want to permit in the empty array.
  def configure_account_update_params
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :firstname, :lastname, :facebook_url, :twitter_url, :linkedin_url) }
  end

  def update_resource(details)

    if current_user.provider || (params[:user][:password].blank? && params[:user][:password_confirmation].blank?)
      @user.update_without_password(details)
    else
      @user.update_with_password(details)
    end
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  invisible_captcha only: [:create]
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	before_action :get_mailbox

	def dashboard	
	  @event = Event.new
	  @conversations = @mailbox.conversations.take(4)
	end

	private
 
  	def get_mailbox
      @mailbox ||= current_user.mailbox
  	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/dashboard.html.erb
<div class="container">
<h1 style="margin: 30px 0;">Hello <%= current_user.firstname %>!</h1>


<div role="tabpanel">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#host" aria-controls="host" role="tab" data-toggle="tab">Host</a></li>
     <li role="presentation"><a href="#inbox" aria-controls="inbox" role="tab" data-toggle="tab">Inbox</a></li>
    <li role="presentation"><a href="<%= edit_user_registration_path %>" aria-controls="profile" role="tab"> Change Profile</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="host">

    	<div class="row">
    		<div class="col-sm-12">
    	     <button data-toggle="modal" href="#myModal3" class="btn btn-primary" style="margin: 30px 0;">Create a post</button>
        </div>
    	</div>

      <% if current_user.events.count > 0 %>

    	<table class="table table-hover">
      <thead>
        <tr>
          <th>Title</th>
          <th>Date</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      <tr>

      <% current_user.events.each do |event| %>  
      <td><%= event.title %></td>
      <td><%=  event.event_date %></td>
      <td>
        <a href="<%= event_path(event) %>" class="btn btn-small">
          <i class="fa fa-eye"></i>
          Show
        </a>
        <a href="<%= edit_event_path(event) %>" class="btn btn-small">
          <i class="fa fa-pencil"></i>
          Edit
        </a>

        <% if event.live %>
          <%= link_to("Pause", "#{event_path(event)}?event[live]=false", method: :patch, class: "btn btn-danger btn-small") %>
        <% else %>
           <%= link_to("Activate", "#{event_path(event)}?event[live]=true", method: :patch, class: "btn btn-primary btn-small") %>
        <% end %> 
      </td>
    </tr>
    <% end %>


      </tbody>
    </table>

    <% end %>

    </div>
    <div role="tabpanel" class="tab-pane" id="inbox">


      <% if @conversations.count > 0 %>

      <h2>Your Conversations</h2>

      <ul class="list-group">
        <%= render partial: 'conversations/conversation', collection: @conversations %>
    </ul>

    <% if @conversations.count > 3 %>

    <div class="row">
      <a href="<%= conversations_path %>" class="btn btn-info more-listings">View all</a>
    </div>

    <% end %>

    <% else %>

    <h2>No messages yet.</h2>

    <% end %>

    </div>
    <div role="tabpanel" class="tab-pane" id="profile">

      <%= link_to "Change your password", edit_user_registration_path %>


    </div>


</div>
</div>
</div>

<div class="modal fade" id="myModal3">
  <div class="modal-dialog">
      <div class="modal-content modal-lg">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h4 class="modal-title">Create a post</h4>
        </div>
        <%= form_for(@event, :html => { :multipart => true }) do |f| %>
        <div class="modal-body">
              <% if @event.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@event.errors.count, "error") %> prohibited this space from being saved:</h2>

                <ul>
                  <% @event.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
                </div>
                <% end %>

                <div class="row">
                <div class="col-sm-7">
                <div class="field">
                  <%= f.label :title %><br />
                  <%= f.text_field :title, autofocus: true  %>
                </div>

                <div class="field">
                  <%= f.label :description %><br />
                  <%= f.text_area :description, size: "40x6" %>
                </div>

                <div class="field">
                  <%= f.label :city %><br />
                  <%= f.text_field :city %>
                </div>

                <div class="field">
                  <%= f.label "Neighbourhood / Nearest-intersection" %><br />
                  <%= f.text_field :near %>
                </div>

                <div class="field">
                  <%= f.label "Date" %><br />
                  <input type="text" class="datepicker" name="event[event_date]" >
                </div>

              </div>

              <div class="col-sm-4 col-sm-offset-1">
                 <div class="field">
                  <%= f.label "Start Time" %><br />
                <%= f.time_select :start_time,  {ampm: true, minute_step: 15} %>  
</div>

<div class="field">
                  <%= f.label "End Time" %><br />
                <%= f.time_select :end_time,  {ampm: true, minute_step: 15} %>
</div>

                <div class="field">
                  <%= f.label "Select Space Type" %><br />
                   <%= f.select :space_type, options_for_select(["Apartment", "House"], @event.space_type) %>
                </div>

                <div class="field">
                  <%= f.label "Select Seats Available" %><br />
                  <%= f.select :seats, options_for_select((1..10).to_a, @event.seats) %>
                </div>

                <div class="field">
                  <%= f.label "Wifi Availability" %><br />
                   <%= f.check_box :wifi? %>
                </div>

                <div class="field">
                  <%= f.label "Got Coffee? :) " %><br />
                  <%= f.check_box :coffee? %>
                </div>

                <div class="field">
                <%= f.label "Change Header Image" %><br />
                <%= f.file_field :header_img %>
                </div>
              </div>
      </div>

    </div>
        
        <div class="modal-footer">
          <a href="#" data-dismiss="modal" class="btn">Close</a>
          <%= f.submit "Create" %>
        </div>
        <% end %>
      </div>
    </div>
</div>

<script>
$('.datepicker').datepicker({
    format: 'yyyy/mm/dd',
})

$('.datepicker').datepicker()
.on('changeDate', function(ev){
 $('.datepicker').datepicker('hide');
 });
</script>

app/views/users/show.html.erb
<p><%= @user.email %></p>
<%= link_to 'Edit', edit_user_registration_path(@user) %> |
<%= link_to 'Back', root_path %>