config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    sessions: "users/sessions", 
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "users/registrations"
  }

  resources :events, :only => [:create]
  get 'e/:id' => 'events#show', as: :event
  get 'e/:id/edit' => 'events#edit', as: :edit_event
  patch 'e/:id' => 'events#update'
  put 'e/:id' => 'events#update'
  
  resources :bookings, :only => [:create, :destroy]

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
    end
  end

  resources :messages, only: [:new, :create]

  root 'pages#home'

  get 'faq' => 'pages#faq', as: :faq

  get 'dashboard' => 'users#dashboard', as: :dash

  get 'c/:city' => 'events#city', as: :city

end

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="container">
    <p>2015 <a href="http://hoffiz.com">hoffiz.com</a></p>
  </div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default nv-hoffiz">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">hoffiz</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to('FAQ', faq_path) %></li>
        <li class="divider"></li>
        <% if user_signed_in? %>
        <li>
        <%= link_to('Dashboard', dash_path) %>        
         </li>
        <li>
        <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
         </li>
      <% else %>
         <li class="hidden-xs"><button data-toggle="modal" href="#signin" type="button" class="btn btn-default navbar-btn">Sign in</button></li>
     
        <li class="visible-xs">
          <%= link_to('Login', new_user_session_path) %>
        </li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>