config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    sessions: "users/sessions", 
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "users/registrations"
  }

  resources :events, :only => [:create]
  get 'e/:id' => 'events#show', as: :event
  get 'e/:id/edit' => 'events#edit', as: :edit_event
  patch 'e/:id' => 'events#update'
  put 'e/:id' => 'events#update'
  
  resources :bookings, :only => [:create, :destroy]

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
    end
  end

  resources :messages, only: [:new, :create]

  root 'pages#home'

  get 'faq' => 'pages#faq', as: :faq

  get 'dashboard' => 'users#dashboard', as: :dash

  get 'c/:city' => 'events#city', as: :city

end

app/models/event.rb
class Event < ActiveRecord::Base

	paginates_per 16

	before_save :assign_slug
	before_save :capitalize_city
	belongs_to :user

	has_attached_file :header_img, :styles => { :medium => "600x400>", :thumb => "450x300>" }, :default_url => "/images/:style/missing.png"

	validates_attachment_content_type :header_img, :content_type => /\Aimage\/.*\Z/

	validates_with AttachmentSizeValidator, :attributes => :header_img, :less_than => 2.megabytes

	def assign_slug
      self.slug = self.title.parameterize
  	end

  	def capitalize_city
      self.city = self.city.capitalize
  	end

  	def to_param
      slug 
  	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  before_action :set_event, only: [:edit, :update, :destroy]

  def show
	  @event = Event.find_by_slug(params[:id])
  end

  def new
    @event = Event.new
  end

  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id

    respond_to do |format|
      if @event.save
        format.html { redirect_to dash_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { redirect_to dash_path, alert: 'Something went wrong. Post was not saved.' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /e/1
  # PATCH/PUT /e/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to dash_path, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def city
    @city = params[:city].capitalize
    @events = Event.where("city = ? AND live = ?", @city, true).page(params[:page])    

    if @events.empty?
      redirect_to root_path
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = current_user.events.find_by_slug(params[:id])
       rescue ActiveRecord::RecordNotFound
        flash[:notice] = "not authorized"
        redirect_to :action => 'index'
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :event_date, :start_time, :end_time, :space_type, :near, :coffee, :wifi, :header_img, :seats, :live, :city )
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event, :html => { :multipart => true }) do |f| %>

<div class="row">
              <% if @event.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@event.errors.count, "error") %> prohibited this space from being saved:</h2>

                <ul>
                  <% @event.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
                </div>
                <% end %>

                <div class="col-sm-5">
                <div class="field">
                  <%= f.label :title %><br />
                  <%= f.text_field :title  %>
                </div>

                <div class="field">
                  <%= f.label :description %><br />
                  <%= f.text_area :description, size: "40x6" %>
                </div>

                <div class="field">
                  <%= f.label :city %><br />
                  <%= f.text_field :city %>
                </div>

                <div class="field">
                  <%= f.label "Neighbourhood / Nearest-intersection" %><br />
                  <%= f.text_field :near %>
                </div>

                <div class="field">
                  <%= f.label "Date" %><br />
                  <input class="datepicker" type="text" name="event[event_date]", value="<%= @event.event_date %>">
                </div>

              </div>

              <div class="col-sm-4 col-sm-offset-1">
                 <div class="field">
                  <%= f.label "Start Time" %><br />
                <%= f.time_select :start_time,  {ampm: true, minute_step: 15} %>  
</div>

<div class="field">
                  <%= f.label "End Time" %><br />
                <%= f.time_select :end_time,  {ampm: true, minute_step: 15} %>
</div>

                <div class="field">
                  <%= f.label "Select Space Type" %><br />
                   <%= f.select :space_type, options_for_select(["Apartment", "House"], @event.space_type) %>
                </div>

                <div class="field">
                  <%= f.label "Select Seats Available" %><br />
                  <%= f.select :seats, options_for_select((1..10).to_a, @event.seats) %>
                </div>

                <div class="field">
                  <%= f.label "Wifi Availability" %><br />
                   <%= f.check_box :wifi? %>
                </div>

                <div class="field">
                  <%= f.label "Got Coffee? :) " %><br />
                  <%= f.check_box :coffee? %>
                </div>

                <div class="field">
                <%= f.label "Change Header Image" %><br />
                <%= f.file_field :header_img %>
                </div>
              </div>

            </div>

            <div class="row">
              <div class="col-sm-4">


  <div class="submit-div" style="margin: 20px 0;">
    <%= f.submit %>
  </div>

</div>



</div>

  <% end %>


  <script>
$('.datepicker').datepicker({
    format: 'yyyy/mm/dd',
  })

$('.datepicker').datepicker()
.on('changeDate', function(ev){
 $('.datepicker').datepicker('hide');
 });
</script>

app/views/events/city.html.erb
<h1 class="text-center"><%= @city %> Hoffizes</h1>

  <div class="col-sm-12">
            
             <div class="row">

              <% @events.each do |event| %>

                <div class="col-sm-3 features">

                    <div>
                    <a href="<%= event_path(event) %>">
        <%= image_tag event.header_img.url(:thumb), title: event.title, class:"img-100" %>
                  </a>

                  <div class="avi-overlay">

      <% if event.user.avatar %>
        <%= image_tag event.user.avatar, class: "media-object"  %>
       <% else %>
          <%= image_tag gravatar_image_url(event.user.email, size: 50, default: "identicon"), title: event.user.firstname %>
      <% end %>

                  </div>

                </div>

                   <div class="space-feats">
                    <span>Seats: <%= event.seats %></span>
                    </div>

                    <a href="<%= event_path(event) %>"><h4 class=""><%= event.title %></h4></a>
                  
                </div>


                <% end %>
              </div>

    </div>
    <%= paginate @events %>

<%#= link_to 'New Space', new_space_path %>

app/views/events/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Back', dash_path %>

 <script>
$('.datepicker').datepicker()
.on('changeDate', function(ev){
 $('.datepicker').datepicker('hide');
 });
 </script>

app/views/events/show.html.erb
<div class="row">
<div class="col-sm-9">

  <% if @event.header_img_file_name %>
    <%= image_tag @event.header_img.url  %>
  <% end %>

<h1><%= @event.title %></h1>
<p><%= @event.description %></p>
</div>

<div class="col-sm-3">
	<% if !@event.live %>
	<h1>Post is offline</h1>
	<% else %>
		<% if (current_user && current_user.id != @event.user_id) %>
		 <a data-toggle="modal" href="#myModal4" class="btn btn-lg btn-primary" role="button">Request Invite</a>
		 <% elsif !current_user %>
			<%= link_to("Request Invite", new_user_session_path, method: :get, class: "btn btn-primary") %>
		<% end %>
	<div class="details-box">
		<h3>Details</h3>
		<div class="details-item">
		<h4>Host: </h4>
		<div class="media">
  <div class="media-left">
    <a href="#">

    	<% if @event.user.avatar %>
    		<%= image_tag @event.user.avatar, class: "media-object"  %>
     	 <% else %>
      		<%= image_tag gravatar_image_url(@event.user.email, size: 64, default: "identicon"), title: @event.user.firstname %>
     	<% end %>
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading"><%= @event.user.firstname %></h4>

    <% if !@event.user.facebook_url.blank? %>
    <a href="<%= @event.user.facebook_url %>"><i class="fa fa-2x fa-facebook"></i></a>
    <% end %>
    <% if !@event.user.linkedin_url.blank? %>
    <a href="<%= @event.user.linkedin_url %>"><i class="fa fa-2x fa-linkedin"></i></a>
    <% end %>
    <% if !@event.user.twitter_url.blank? %>
    <a href="<%= @event.user.twitter_url %>"><i class="fa fa-2x fa-twitter"></i></a>
    <% end %>
  </div>
</div>
		</div>
		<div class="details-item">
		<h4>Location near</h4>
		<p><%= @event.near %> </p>
		<h4>Available Seats:</h4>
		<p><%= @event.seats %></p>
		</div>
		<div class="details-item">
		<h4>Date: </h4>
		<p><%= (@event.event_date).strftime("%a, %d %b") %></p>
		<h4>Time: </h4>
		<p><%= "#{@event.start_time.strftime("%-I:%M%p")} - #{@event.end_time.strftime("%-I:%M%p")}" %></p>
		</div>
		<div class="details-item">
			<% if @event.wifi %>
				<i class="fa fa-2x fa-wifi"></i> <p>Available</p>
			<% end %>
			<% if @event.coffee %>
			<i class="fa fa-2x fa-coffee"></i> <p>Available</p>
			<% end %>
		</div>
	</div>

	<% end %>

</div>

<div class="fb-comments" data-href="<%= event_url(@event) %>" data-width="470" data-num-posts="2"></div>


</div>

<div class="modal" id="myModal4">
	<div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h4 class="modal-title">Send Message</h4>
        </div>
        <%= form_tag messages_path, method: :post do %>
        <div class="modal-body">
<div class="row">
<div class="col-sm-12">
  <div class="form-group">
    <%= label_tag 'message[subject]', 'Subject' %>
    <%= text_field_tag 'message[subject]', nil, class: 'form-control', required: true %>
  </div>
 
  <div class="form-group">
    <%= label_tag 'message[body]', 'Message' %>
    <%= text_area_tag 'message[body]', nil, cols: 3, class: 'form-control', required: true %>
  </div>
 
  <%= hidden_field_tag 'message[event_id]', @event.id %>
  <%= hidden_field_tag 'message[slug]', @event.slug %>
  <%= invisible_captcha %>
   
</div>

</div>
        </div>
        <div class="modal-footer">
          <a href="#" data-dismiss="modal" class="btn">Close</a>
          <%= submit_tag "Send" %>
        </div>
        <% end %>
      </div>
    </div>
</div>

<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=504323752911178";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<%#= link_to 'Edit', edit_space_path(@space) %>
<%#= link_to 'Back', spaces_path %>