config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    sessions: "users/sessions", 
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "users/registrations"
  }

  resources :events, :only => [:create]
  get 'e/:id' => 'events#show', as: :event
  get 'e/:id/edit' => 'events#edit', as: :edit_event
  patch 'e/:id' => 'events#update'
  put 'e/:id' => 'events#update'
  
  resources :bookings, :only => [:create, :destroy]

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
    end
  end

  resources :messages, only: [:new, :create]

  root 'pages#home'

  get 'faq' => 'pages#faq', as: :faq

  get 'dashboard' => 'users#dashboard', as: :dash

  get 'c/:city' => 'events#city', as: :city

end

app/views/pages/faq.html.erb
<h1 class="text-center">Frequently Asked Questions</h1>

<h3>What is this all about?<h3>
<p>Bringing together individuals with flexible work space needs, thereby creating a network of temporary and amazing workplaces in each other's homes. Hoffiz is a web platform inspired by the Hoffice movement in Europe. Let's do some great work and meet some great people!</p>

<h4>More resources to come! Send feedback to: hello@hoffiz.com ;)</h4>

app/views/pages/home.html.erb
<div class="jumbotron">
        <h1>Why work alone?</h1>
        <p class="lead">Host co-working sessions from home. Meet new people.</p>
        
        <% if current_user %>
        <a data-toggle="modal" href="<%= dash_path %>" class="btn btn-lg btn-success" role="button">Become a host</a>
        <% else %>
        <a data-toggle="modal" href="#signup" class="btn btn-lg btn-success" role="button">Become a host</a>
        <% end %>
        <a href="#listings" class="btn btn-lg btn-info" role="button">Find a host</a>
      </div>

	<h2 id="listings" class="text-center">It's happening in Toronto</h2>
  <a data-toggle="modal" href="#signup" ><h4 class="text-center">Add your city? <i class="fa fa-smile-o"></i></h4></a>

  <div class="row">
	<div class="col-sm-12">

            	<% @events.each do |event| %>

                <div class="col-sm-4 features">

                  <div>
                    <a href="<%= event_path(event) %>">
        <%= image_tag event.header_img.url(:thumb), title: event.title, class:"img-100" %>
                  </a>

                  <div class="avi-overlay">

      <% if event.user.avatar %>
        <%= image_tag event.user.avatar, class: "media-object"  %>
       <% else %>
          <%= image_tag gravatar_image_url(event.user.email, size: 50, default: "identicon"), title: event.user.firstname %>
      <% end %>

                  </div>

                </div>

                   <div class="space-feats">
                    <span>Seats: <%= event.seats %></span>
                    </div>

                    <a href="<%= event_path(event) %>"><h4 class=""><%= event.title %></h4></a>
                  
                </div>

                <% end %>
              
    </div>
</div>
<div class="row">

    <a href="<%= city_path('toronto') %>" class="btn btn-info more-listings">View More...</a>
   </div>